### ISSUE TITLE
Marko exceptions not throwing the entire stack trace when

### ISSUE THREAD

**Issue by pedramphp** [raptorjs/marko#25]
We are getting errors similar to what we see below, it will be great to get the entire stack trace here so we know what line has is the problem.

```
ERROR r1coltv/src/controllers/dealsHub: { '0': [TypeError: Cannot read property 'left' of undefined] } bad error
```

**Comment by patrick-steele-idem** [comment]
Can you provide more details or a reproducible test? I have not run into a case where the stack trace was not valid. Are you sure the problem does not reside in your code?

**Comment by patrick-steele-idem** [comment]
@pedramphp ping. Can you please provide more details?

**Comment by pedramphp** [comment]
Try accessing a property of an object which doesn't exist in the `renderer.js`.

**Comment by pedramphp** [comment]
```
ERROR r1coltv/src/controllers/dealsHub: { '0': [TypeError: Cannot read property 'a' of null] } bad error
```

try running the code below

renderer.js
```
module.exports = function render(input, context) {
	var t = null;
	var a = t.a;
	console.log("asdasd", a);
	var model = getTemplateModel(input);
	if (model) {
		if(model.options.mode === 'large'){
			largeTemplate.render(model, context);
		}else{
			template.render(model, context);
		}
	}
};
```

**Comment by patrick-steele-idem** [comment]
I just created a project to try and reproduce and I am not able to reproduce the problem. Here is the error that I see logged:

```
/Users/psteeleidem/temp/marko-issue-25/components/app-foo/renderer.js:3
    var a = t.a;
             ^
TypeError: Cannot read property 'a' of null
    at Function.module.exports (/Users/psteeleidem/temp/marko-issue-25/components/app-foo/renderer.js:3:14)
    at module.exports.t (/Users/psteeleidem/temp/marko-issue-25/node_modules/marko/runtime/helpers.js:127:14)
    at render (/Users/psteeleidem/temp/marko-issue-25/template.marko.js:9:5)
    at Object.Template.render (/Users/psteeleidem/temp/marko-issue-25/node_modules/marko/runtime/marko-runtime.js:126:9)
    at Object.<anonymous> (/Users/psteeleidem/temp/marko-issue-25/index.js:2:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Please check your project.
